### ISSUE TITLE
comparison on new algorithms

### ISSUE THREAD

**Issue by JVision** [thomas-koehler/SupER#1]
Hi Thomas,

I've come across your paper on the web, was pretty impressed by the conclusion: classic algorithms work as well as if not better than Deep learning methods.

do you have a chance to benchmark it on up-to-date algorithms, especially for those Deep Learning-based methods which are doing well on NITRE 2018 and PRIME 2018?

It would also be great to re-write your code in Python if possible.

Best,
JVision

**Comment by thomas-koehler** [comment]
Hi,

Thank you very much for your feedback concerning our benchmark. Regarding the evaluation of newer algorithms from other authors, we currently offer two options:

- Option 1: Other authors can run the benchmark themselves using our evaluation scripts. We will review submitted results and publish them accordingly.
- Option 2: Other authors can provide a self-contained wrapper function for their source code (potentially with third-party dependencies and required training scripts in case of learning-based methods). In that case we include the method to the benchmark and run the evaluation on our servers.

We also use the data for own publications in the future and share all new results in the result section on our project website (https://superresolution.tf.fau.de/) from time to time.

Best,

Thomas
