### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by makslevental** [thomas-koehler/SupER#2]
https://github.com/thomas-koehler/SupER/blob/master/matlab/algorithms/SRAlgorithms/superresolve_aplus.m#L60

should be 

```matlab
for d=10:-1:1
```

**Comment by thomas-koehler** [comment]
Hi,

the d loops over the dictionary sizes. According to the reference implementation of A+ provided by the authors, d = 10 is correct. In principle, you are free to choose other sizes bit I did not modified the parameters of A+ and re-used the original source codes as far as possible for the benchmark.

Best,

Thomas
