### ISSUE TITLE
various syntax errors

### ISSUE THREAD

**Issue by makslevental** [thomas-koehler/SupER#3]
https://github.com/thomas-koehler/SupER/blob/master/matlab/algorithms/SRAlgorithms/DRCN/snu_matconvnet/matlab/+dagnn/@DagNN/print.m#L48

https://github.com/thomas-koehler/SupER/blob/master/matlab/algorithms/SRAlgorithms/VDSR/matconvnet/matlab/simplenn/vl_simplenn_tidy.m#L57

**Comment by thomas-koehler** [comment]
Hi,

Thank you very much for pointing that out. The errors were caused by the matconvnet version required for VDSR and DRCN.

Best,

Thomas
