### ISSUE TITLE
Which one is SR image for a series of LR images?

### ISSUE THREAD

**Issue by axhiao** [thomas-koehler/SupER#5]
The input of Multi-Frame Super Resolution(MFSR)  is a series of low resolution images. And the output is a single high resolutiono image. For your dataset, if I want to use it for MFSR, I can see there are a series of 40 images as input. But which one should I use for the single high resolution output image? Thank you.

**Comment by thomas-koehler** [comment]
Dear axhiao,

I am sorry for my late response.

You are right, all MFSR algorithms in the benchmark provide a single high-resolution image for a set of low-resolution input images. However, in our evaluation protocol all algorithms are applied in a **sliding window** scheme. That is, given a window size of K frames and n low-resolution frames y[1] … y[n] (we use n = 40), we use y[1] … y[K] to obtain the first high-resolution image, y[2] … y[K+1] to obtain the second high-resolution image, and so on. For each sliding window, the central frame is chosen as a reference. By default, we use different window sizes (K = 5, 7, 17) for different magnification factors (2, 3, and 4) and process 10 sliding windows for each dataset, i.e. you get 10 high-resolution images for each input dataset. We used these parameters settings for the benchmark reported in our paper (see Section 4.1 in our TPAMI paper for more details) and averaged quantitative results over these sledding windows. Using only a single window comprising all K = 40 frames might lead to a higher bias compared to averaging over multiple windows.

However, you are free to set other parameters for own experiments and there are scripts to configure all benchmark parameters. For instance, in initEvaluationParametersForBaseline.m you can set the parameters for all baseline experiments comprising our benchmark for global, local, and mixed motion. If you would set numberOfFrames = [40, 40, 40] and sliding_val = 1, a single sliding window is processed (using startReferenceFrame as reference for motion estimation).

I hope that these explanation help.

Best,

Thomas
